"""Skill 机制的通用常量。"""

MAX_SKILL_FILE_SIZE = 10 * 1024 * 1024
MAX_SKILL_NAME_LENGTH = 64
MAX_SKILL_DESCRIPTION_LENGTH = 1024
MAX_SKILL_COMPATIBILITY_LENGTH = 500
MAX_LOAD_WARNINGS = 20
MAX_LOAD_WARNING_LENGTH = 1000
WARNING_TRUNCATION_SUFFIX = "... [已截断]"
